Config({
    "network-name": "باب المندب",
    "service-number": "773093894",
    "login-type": "User",
    "news-line": "",
    "input-type": "",
    "input-autocomplete": "off",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "input-to-tel-type-when": 0,
    "enable-hot-cookie": 1,
    "enable-hot-blocker": 1,
    "price-button": true,
    "sell-point-button": true,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 5,
    "try-count": 5,
    "redirect-to-esterahah": "",
    "redirect-to-mobasher": "",
    "show-date-field": false,
    "profiles": [],
    "sell-points": []
})